package entity;
// Generated 11/05/2017 01:28:51 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsr;
     private String nombre;
     private String tipoUsr;
     private String correo;
     private String password;

    public Usuario() {
    }

    public Usuario(String nombre, String tipoUsr, String correo, String password) {
       this.nombre = nombre;
       this.tipoUsr = tipoUsr;
       this.correo = correo;
       this.password = password;
    }
   
    public Integer getIdUsr() {
        return this.idUsr;
    }
    
    public void setIdUsr(Integer idUsr) {
        this.idUsr = idUsr;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipoUsr() {
        return this.tipoUsr;
    }
    
    public void setTipoUsr(String tipoUsr) {
        this.tipoUsr = tipoUsr;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


